language: python
python:
    - 2.6
    - 2.7
    - 3.2
install: pip install -r requirements.txt
script: tox
before_install:
    - sudo apt-get update
    - sudo apt-get install build-essential python-dev python-pip
